GET http://localhost:3000/anime

###

GET http://localhost:3000/anime/606b026b70adca099454d6ae


###

POST http://localhost:3000/anime
Content-Type: application/json

# {
#     "sources": [
#         "https://anime-planet.com/anime/code-geass-movie-lelouch-of-the-resurrection"
#       ],
#       "title": "Code Geass Movie: Lelouch of the Re;surrection",
#       "type": "Movie",
#       "episodes": 1,
#       "status": "FINISHED",
#       "year": 2019,
#       "synonyms": [
#         "Code Geass Movie: Fukkatsu no Lelouch"
#       ],
#       "tags": [
#         "action",
#         "drama",
#         "mecha",
#         "original work",
#         "real robot",
#         "sci fi",
#         "superpowers"
#       ],
#       "rating": 9.81
# }

{
      "sources": [
          "https://anidb.net/anime/4563",
          "https://anilist.co/anime/1535",
          "https://anime-planet.com/anime/death-note",
          "https://kitsu.io/anime/1376",
          "https://myanimelist.net/anime/1535",
          "https://notify.moe/anime/0-A-5Fimg"
          ],
          "title": "Death Note",
          "type": "TV",
          "episodes": 37,
          "status": "FINISHED",
          "year": 2006,
          "synonyms": [
              "Caderno da Morte",
              "DEATH NOTE",
              "DN",
              "Death Note - A halállista",
              "Death Note - Carnetul morţii",
              "Death Note - Zápisník smrti",
              "Mirties Užrašai",
              "Notatnik śmierci",
              "Notes Śmierci",
              "Quaderno della Morte",
              "Sveska Smrti",
              "Ölüm Defteri",
              "Τετράδιο Θανάτου",
              "Бележник на Смъртта",
              "Записник Смерті",
              "Свеска Смрти",
              "Тетрадка на Смъртта",
              "Тетрадь cмерти",
              "Үхлийн Тэмдэглэл",
              "מחברת המוות",
              "دفترچه مرگ",
              "دفترچه یادداشت مرگ",
              "كـتـاب الـموت",
              "مدونة الموت",
              "مذكرة الموت",
              "موت نوٹ",
              "डेथ नोट",
              "ですのーと",
              "デスノート",
              "死亡笔记",
              "데스노트"
          ],
          "tags": [
              "alternative present",
              "amnesia",
              "anti-hero",
              "asia",
              "based on a manga",
              "contemporary fantasy",
              "cops",
              "crime",
              "criminals",
              "demons",
              "detective",
              "detectives",
              "drama",
              "earth",
              "espionage",
              "gods",
              "japan",
              "male protagonist",
              "manga",
              "mind games",
              "mystery",
              "overpowered main characters",
              "philosophy",
              "plot continuity",
              "police",
              "present",
              "primarily adult cast",
              "primarily male cast",
              "psychological",
              "psychopaths",
              "revenge",
              "rivalries",
              "secret identity",
              "serial killers",
              "shinigami",
              "shounen",
              "supernatural",
              "thriller",
              "time skip",
              "tragedy",
              "urban",
              "urban fantasy",
              "vigilantes",
              "work"
          ],
          "rating": 9.2
}
### 
DELETE http://localhost:3000/anime/606b276154dfa28afcd62451

### 
PUT http://localhost:3000/anime/606b291754dfa28afcd62456
{
      "sources": [
          "https://anidb.net/anime/4563",
          "https://anilist.co/anime/1535",
          "https://anime-planet.com/anime/death-note",
          "https://kitsu.io/anime/1376",
          "https://myanimelist.net/anime/1535",
          "https://notify.moe/anime/0-A-5Fimg"
          ],
          "title": "Death Note",
          "type": "TV",
          "episodes": 37,
          "status": "FINISHED",
          "year": 2006,
          "synonyms": [
              "Caderno da Morte",
              "DEATH NOTE",
              "DN",
              "Death Note - A halállista",
              "Death Note - Carnetul morţii",
              "Death Note - Zápisník smrti",
              "Mirties Užrašai",
              "Notatnik śmierci",
              "Notes Śmierci",
              "Quaderno della Morte",
              "Sveska Smrti",
              "Ölüm Defteri",
              "Τετράδιο Θανάτου",
              "Бележник на Смъртта",
              "Записник Смерті",
              "Свеска Смрти",
              "Тетрадка на Смъртта",
              "Тетрадь cмерти",
              "Үхлийн Тэмдэглэл",
              "מחברת המוות",
              "دفترچه مرگ",
              "دفترچه یادداشت مرگ",
              "كـتـاب الـموت",
              "مدونة الموت",
              "مذكرة الموت",
              "موت نوٹ",
              "डेथ नोट",
              "ですのーと",
              "デスノート",
              "死亡笔记",
              "데스노트"
          ],
          "tags": [
              "alternative present",
              "amnesia",
              "anti-hero",
              "asia",
              "based on a manga",
              "contemporary fantasy",
              "cops",
              "crime",
              "criminals",
              "demons",
              "detective",
              "detectives",
              "drama",
              "earth",
              "espionage",
              "gods",
              "japan",
              "male protagonist",
              "manga",
              "mind games",
              "mystery",
              "overpowered main characters",
              "philosophy",
              "plot continuity",
              "police",
              "present",
              "primarily adult cast",
              "primarily male cast",
              "psychological",
              "psychopaths",
              "revenge",
              "rivalries",
              "secret identity",
              "serial killers",
              "shinigami",
              "shounen",
              "supernatural",
              "thriller",
              "time skip",
              "tragedy",
              "urban",
              "urban fantasy",
              "vigilantes",
              "work"
          ],
          "rating": 9.0
}